### ISSUE TITLE
Poor graphics, lots of warning etc (OSX)

### ISSUE THREAD

**Issue by joelcnz** [gecko0307/atrium#10]
Joels-MacBook-Pro:atrium joelcnz$ dub
Performing "debug" build using dmd for x86_64.
atrium 0.0.5+commit.33.gb8fcc4c: building configuration "atrium"...
atrium.d(218,12): Warning: instead of C-style syntax, use D-style syntax 'ALuint[2] footstepBuffer'
derelict/freetype/ftfuncs.d(165,69): Warning: instead of C-style syntax, use D-style syntax 'FT_Bytes[FT_VALIDATE_GX_LENGTH] tables'
derelict/opengl/exttypes.d(3371,14): Warning: instead of C-style syntax, use D-style syntax 'char[32] DeviceName'
derelict/opengl/exttypes.d(3372,14): Warning: instead of C-style syntax, use D-style syntax 'char[128] DeviceString'
derelict/opengl/glx.d(91,9): Warning: instead of C-style syntax, use D-style syntax 'int[24] pad'
derelict/sdl/macinit/SDLMain.d(379,18): Warning: instead of C-style syntax, use D-style syntax 'char[MAXPATHLEN] parentdir'
derelict/sdl/macinit/runtime.d(102,15): Warning: instead of C-style syntax, use D-style syntax 'objc_ivar[1] ivar_list'
derelict/sdl/macinit/runtime.d(122,17): Warning: instead of C-style syntax, use D-style syntax 'objc_method[1] method_list'
derelict/sdl/macinit/runtime.d(129,12): Warning: instead of C-style syntax, use D-style syntax 'Method[1] buckets'
derelict/sdl/macinit/runtime.d(136,15): Warning: instead of C-style syntax, use D-style syntax 'Protocol_[1] list'
derelict/sdl/sdltypes.d(139,53): Warning: instead of C-style syntax, use D-style syntax 'void function(SDL_AudioCVT_ cvt, Uint16 format)[10] filters'
derelict/sdl/sdltypes.d(210,17): Warning: instead of C-style syntax, use D-style syntax 'SDL_CDtrack[SDL_MAX_TRACKS + 1] track'
derelict/sdl/sdltypes.d(820,12): Warning: instead of C-style syntax, use D-style syntax 'Uint8_[2] save'
derelict/util/wintypes.d(213,29): Warning: instead of C-style syntax, use D-style syntax 'RGBQUAD[1] bmiColors'
dgl/core/event.d(81,10): Warning: instead of C-style syntax, use D-style syntax 'bool[512] keyPressed'
dgl/core/event.d(82,10): Warning: instead of C-style syntax, use D-style syntax 'bool[255] mouseButtonPressed'
derelict/util/compat.d(118,16): Deprecation: module std.c.string is deprecated - Import core.stdc.string instead
derelict/sdl/sdltypes.d(38,16): Deprecation: module std.c.stdio is deprecated - Import core.stdc.stdio instead
derelict/sdl/sdlfuncs.d(41,16): Deprecation: module std.c.stdio is deprecated - Import core.stdc.stdio instead
derelict/sdl/macinit/SDLMain.d(27,16): Deprecation: module std.c.linux.linux is deprecated - Import the appropriate core.sys.posix._ modules instead
derelict/sdl/macinit/SDLMain.d(28,16): Deprecation: module std.c.stdlib is deprecated - Import core.stdc.stdlib or core.sys.posix.stdlib instead
derelict/sdl/macinit/SDLMain.d(29,16): Deprecation: module std.c.string is deprecated - Import core.stdc.string instead
game/audio.d(6,8): Deprecation: module std.c.stdio is deprecated - Import core.stdc.stdio instead
game/audio.d(7,8): Deprecation: module std.c.stdlib is deprecated - Import core.stdc.stdlib or core.sys.posix.stdlib instead
derelict/sdl/macinit/NSEnumerator.d(66,18): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.init with derelict.sdl.macinit.NSEnumerator.NSEnumerator.init deprecated; add 'override' attribute
derelict/sdl/macinit/NSArray.d(67,13): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.init with derelict.sdl.macinit.NSArray.NSArray.init deprecated; add 'override' attribute
derelict/sdl/macinit/NSString.d(77,14): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.init with derelict.sdl.macinit.NSString.NSString.init deprecated; add 'override' attribute
derelict/sdl/macinit/NSMenuItem.d(69,16): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.init with derelict.sdl.macinit.NSMenuItem.NSMenuItem.init deprecated; add 'override' attribute
derelict/sdl/macinit/NSMenu.d(69,12): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.init with derelict.sdl.macinit.NSMenu.NSMenu.init deprecated; add 'override' attribute
derelict/sdl/macinit/NSApplication.d(75,19): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.init with derelict.sdl.macinit.NSApplication.NSApplication.init deprecated; add 'override' attribute
derelict/sdl/macinit/NSAutoreleasePool.d(66,23): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.init with derelict.sdl.macinit.NSAutoreleasePool.NSAutoreleasePool.init deprecated; add 'override' attribute
derelict/sdl/macinit/NSAutoreleasePool.d(72,10): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.release with derelict.sdl.macinit.NSAutoreleasePool.NSAutoreleasePool.release deprecated; add 'override' attribute
derelict/sdl/macinit/NSDictionary.d(66,18): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.init with derelict.sdl.macinit.NSDictionary.NSDictionary.init deprecated; add 'override' attribute
derelict/sdl/macinit/NSNotification.d(66,20): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.init with derelict.sdl.macinit.NSNotification.NSNotification.init deprecated; add 'override' attribute
derelict/sdl/macinit/NSProcessInfo.d(67,19): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.init with derelict.sdl.macinit.NSProcessInfo.NSProcessInfo.init deprecated; add 'override' attribute
derelict/sdl/macinit/SDLMain.d(302,20): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSApplication.NSApplication.init with derelict.sdl.macinit.SDLMain.SDLApplication.init deprecated; add 'override' attribute
derelict/sdl/macinit/SDLMain.d(350,13): Deprecation: implicitly overriding base class method derelict.sdl.macinit.NSObject.NSObject.init with derelict.sdl.macinit.SDLMain.SDLMain.init deprecated; add 'override' attribute
dlib/geometry/ray.d(46,5): Deprecation: constructor dlib.geometry.ray.Ray.this all parameters have default arguments, but structs cannot have default constructors.
game/weapon.d(39,16): Deprecation: implicitly overriding base class method dgl.graphics.entity.Entity.getTransformation with game.weapon.Weapon.getTransformation deprecated; add 'override' attribute
dlib.container.aarray is deprecated, use dlib.container.dict instead
derelict/opengl/extloader.d(134,9): Warning: use std.algorithm.sort instead of .sort property
derelict/opengl/extloader.d(153,9): Warning: use std.algorithm.sort instead of .sort property
derelict/sdl/macinit/SDLMain.d(105,15): Deprecation: derelict.util.loader.SharedLibLoader.bindFunc is not visible from module SDLMain
dmech/mpr.d(312,5): Warning: statement is not reachable
Linking...
Running ./atrium 
Allocated memory: 0 byte(s)
OpenAL device: HDMI
GLSL: error in fragment shader:
ERROR: 0:194: Invalid call of undeclared identifier 'texture2DLod'
ERROR: 0:195: Invalid call of undeclared identifier 'texture2DLod'
ERROR: 0:258: Use of undeclared identifier 'ambTex'
ERROR: 0:258: Use of undeclared identifier 'ambTexSpec'
ERROR: 0:259: Use of undeclared identifier 'c1'
ERROR: 0:259: Use of undeclared identifier 'ambTexSpec'
ERROR: 0:261: Use of undeclared identifier 'c2'
ERROR: 0:263: Use of undeclared identifier 'finalColor'

Allocated memory: 0 byte(s)
Joels-MacBook-Pro:atrium joelcnz$

**Comment by gecko0307** [comment]
It seems that you don't have GL_EXT_shader_texture_lod. I'm testing the game with GeForce GT 740 with latest drivers under Windows. Not sure about how well OpenGL extensions are supported on Mac.

**Comment by joelcnz** [comment]
Ok, thanks for the reply.
