### ISSUE TITLE
64bit libsdl.so missing

### ISSUE THREAD

**Issue by clinei** [gecko0307/atrium#3]
Perhaps add it and load correct version depending on bitness?

**Comment by clinei** [comment]
Wrong library, sorry.
The failing line is 
https://github.com/gecko0307/dgl/blob/gc-free/dgl/core/application.d#L186

**Comment by gecko0307** [comment]
I actually never tried to build it for x86_64. But it is known to work in 32-bit mode under 64-bit Windows 8.

**Comment by clinei** [comment]
I just got it working on 64bit linux with LDC and DMD. Required adding the libs, loading the correct ones and a few changes to dub.json.
I'll make a pull request soon.

**Comment by WebFreak001** [comment]
I know this is old but for people on linux who want to play it using dub: If it crashes because it can't find some library or they are not built for your platform, just install the required libraries via your package manager and build the project using `env USE_SYSTEM_LIBS=true dub`

**Comment by gecko0307** [comment]
Actually, setting `USE_SYSTEM_LIBS` is required only at runtime, not compile time. If it is not set, the game will just try to load local libs.
