### ISSUE TITLE
No graphics in OS X

### ISSUE THREAD

**Issue by p0nce** [gecko0307/atrium#9]
I have already encountered this, it is solved by using SDL v2 instead of SDL v1.

**Comment by gecko0307** [comment]
I'm afraid there's no quick way of porting Atrium to SDL2 due to serious API changes. I'm working on this, but can't promise this work will be finished soon. Actually, Atrium is known to work on OSX (https://github.com/gecko0307/atrium/issues/2), maybe the problem is somewhere else.
